# Generated by Django 4.1.5 on 2023-01-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.PositiveBigIntegerField()),
                ('country', models.CharField(max_length=100, unique=True)),
                ('president', models.CharField(max_length=100)),
            ],
        ),
    ]
