# Generated by Django 4.1.5 on 2023-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('manufacturing_date', models.DateTimeField()),
            ],
        ),
    ]
