# Generated by Django 4.1.5 on 2023-01-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_fruits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Fruit',
        ),
    ]
