# Generated by Django 4.1.5 on 2023-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_fruit_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
