# Generated by Django 4.1.5 on 2023-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_alter_manufacturer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
